In [201]:
import numpy as np
import pandas as pd

**Pandas** - CSV, Excel, SQL cədvəllərlə və s. data topluları ilə işləmək üçün kitabxanadır

In [202]:
my_index = ["Baku", "Sumqayit", "Gence", "Quba"]
my_index

['Baku', 'Sumqayit', 'Gence', 'Quba']

In [203]:
my_data = [2_351_300,  427_600, 331_000, 53_858]
my_data

[2351300, 427600, 331000, 53858]

# Pandas Series

In [204]:
my_series= pd.Series(data=my_data, index=my_index)

In [205]:
my_series

Baku        2351300
Sumqayit     427600
Gence        331000
Quba          53858
dtype: int64

In [206]:
my_series["Baku"]

np.int64(2351300)

In [207]:
my_series["Sumqayit"]

np.int64(427600)

In [208]:
ages = {"Sam":15, "Bob":25, "Sally":32, "John":35}
ages

{'Sam': 15, 'Bob': 25, 'Sally': 32, 'John': 35}

In [209]:
pd.Series(ages)

Sam      15
Bob      25
Sally    32
John     35
dtype: int64

In [210]:
q1 = {"Baku":250, "Sumqayit":200, "Ganja":300, "Quba":400}
q2 = {"Xirdalan":135, "Ganja":200, "Qusar":150, "Baku":135}
q1, q2

({'Baku': 250, 'Sumqayit': 200, 'Ganja': 300, 'Quba': 400},
 {'Xirdalan': 135, 'Ganja': 200, 'Qusar': 150, 'Baku': 135})

In [211]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)
sales_q1, sales_q2

(Baku        250
 Sumqayit    200
 Ganja       300
 Quba        400
 dtype: int64,
 Xirdalan    135
 Ganja       200
 Qusar       150
 Baku        135
 dtype: int64)

In [212]:
sales_q1.keys()

Index(['Baku', 'Sumqayit', 'Ganja', 'Quba'], dtype='str')

In [213]:
sales_q1.values

array([250, 200, 300, 400])

In [214]:
sales_q1 * 2

Baku        500
Sumqayit    400
Ganja       600
Quba        800
dtype: int64

In [215]:
sales_q1

Baku        250
Sumqayit    200
Ganja       300
Quba        400
dtype: int64

In [216]:
sales_q2

Xirdalan    135
Ganja       200
Qusar       150
Baku        135
dtype: int64

In [217]:
sales_q1 + sales_q2

Baku        385.0
Ganja       500.0
Quba          NaN
Qusar         NaN
Sumqayit      NaN
Xirdalan      NaN
dtype: float64

In [218]:
first_half = sales_q1.add(sales_q2, fill_value=0)
first_half

Baku        385.0
Ganja       500.0
Quba        400.0
Qusar       150.0
Sumqayit    200.0
Xirdalan    135.0
dtype: float64

# Pandas DataFrame

In [219]:
my_columns = ["Jan", "Feb", "Mar"]

In [220]:
np.random.seed(42)
my_data = np.random.randint(10, 100, (4, 3))
my_data

array([[61, 24, 81],
       [70, 30, 92],
       [96, 84, 84],
       [97, 33, 12]], dtype=int32)

In [221]:
df = pd.DataFrame(data=my_data, columns=my_columns, index=my_index)
df

          Jan  Feb  Mar
Baku       61   24   81
Sumqayit   70   30   92
Gence      96   84   84
Quba       97   33   12

In [222]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Baku to Quba
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [223]:
employee_data = pd.read_csv('datas/employees.csv')

In [224]:
employee_data

,ID,Name,Age,Country,Salary,ExperienceYears,Remote,Department
0,1,Lucy,56,USA,30854.0,15.0,Yes,IT
1,2,Victoria,46,Azerbaijan,68623.0,11.0,Yes,HR
2,3,Benjamin,32,Germany,37392.0,NaN,No,Marketing
3,4,Luna,25,USA,85680.0,13.0,No,Finance
4,5,Zoe,38,Brazil,76717.0,5.0,Yes,Design
...,...,...,...,...,...,...,...,...
95,96,Abigail,59,USA,52399.0,16.0,Yes,Finance
96,97,Harper,56,USA,76214.0,18.0,Yes,IT
97,98,Owen,58,France,116416.0,4.0,No,Design
98,99,Ethan,45,USA,100271.0,8.0,Yes,Design
99,100,Grayson,24,Germany,74064.0,11.0,Yes,HR

In [225]:
employee_data.columns

Index(['ID', 'Name', 'Age', 'Country', 'Salary', 'ExperienceYears', 'Remote',
       'Department'],
      dtype='str')

In [226]:
employee_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               100 non-null    int64
 1   Name             100 non-null    str
 2   Age              100 non-null    int64
 3   Country          99 non-null     str
 4   Salary           98 non-null     float64
 5   ExperienceYears  98 non-null     float64
 6   Remote           100 non-null    str
 7   Department       99 non-null     str
dtypes: float64(2), int64(2), str(4)
memory usage: 6.4 KB

In [227]:
employee_data.head()

   ID      Name  Age     Country   Salary  ExperienceYears Remote Department
0   1      Lucy   56         USA  30854.0             15.0    Yes         IT
1   2  Victoria   46  Azerbaijan  68623.0             11.0    Yes         HR
2   3  Benjamin   32     Germany  37392.0              NaN     No  Marketing
3   4      Luna   25         USA  85680.0             13.0     No    Finance
4   5       Zoe   38      Brazil  76717.0              5.0    Yes     Design

In [228]:
employee_data.head(8)

   ID       Name  Age     Country    Salary  ExperienceYears Remote Department
0   1       Lucy   56         USA   30854.0             15.0    Yes         IT
1   2   Victoria   46  Azerbaijan   68623.0             11.0    Yes         HR
2   3   Benjamin   32     Germany   37392.0              NaN     No  Marketing
3   4       Luna   25         USA   85680.0             13.0     No    Finance
4   5        Zoe   38      Brazil   76717.0              5.0    Yes     Design
5   6  Sebastian   56       Japan  117092.0              5.0    Yes     Design
6   7    Paisley   36      France   80859.0             12.0     No    Finance
7   8      Jaxon   40  Azerbaijan   56309.0             18.0     No         HR

In [229]:
employee_data.tail()

     ID     Name  Age  Country    Salary  ExperienceYears Remote Department
95   96  Abigail   59      USA   52399.0             16.0    Yes    Finance
96   97   Harper   56      USA   76214.0             18.0    Yes         IT
97   98     Owen   58   France  116416.0              4.0     No     Design
98   99    Ethan   45      USA  100271.0              8.0    Yes     Design
99  100  Grayson   24  Germany   74064.0             11.0    Yes         HR

In [230]:
employee_data.tail(13)

,ID,Name,Age,Country,Salary,ExperienceYears,Remote,Department
87,88,Stella,41,Germany,32869.0,2.0,No,Design
88,89,Hannah,28,Azerbaijan,91135.0,7.0,No,Marketing
89,90,Addison,34,Azerbaijan,80108.0,19.0,Yes,Marketing
90,91,Skylar,25,Brazil,68467.0,15.0,No,HR
91,92,John,52,Germany,53328.0,12.0,Yes,Finance
92,93,Samuel,52,France,116831.0,17.0,Yes,IT
93,94,Nora,50,USA,33987.0,9.0,Yes,HR
94,95,Penelope,22,Japan,88871.0,18.0,Yes,HR
95,96,Abigail,59,USA,52399.0,16.0,Yes,Finance
96,97,Harper,56,USA,76214.0,18.0,Yes,IT
97,98,Owen,58,France,116416.0,4.0,No,Design
98,99,Ethan,45,USA,100271.0,8.0,Yes,Design
99,100,Grayson,24,Germany,74064.0,11.0,Yes,HR

In [231]:
employee_data.sample(7)

    ID     Name  Age     Country    Salary  ExperienceYears Remote Department
44  45    David   37       Japan   38155.0              7.0     No    Finance
4    5      Zoe   38      Brazil   76717.0              5.0    Yes     Design
53  54   Amelia   21  Azerbaijan   76843.0             12.0     No         IT
42  43   Nathan   43     Germany   67504.0              1.0     No         IT
10  11    Logan   41      France  100467.0              0.0     No         HR
85  86      Leo   18      Brazil   51357.0             19.0     No     Design
72  73  Matthew   33      France   59299.0              5.0    Yes    Finance

In [232]:
employee_data.describe()

               ID         Age         Salary  ExperienceYears
count  100.000000  100.000000      98.000000        98.000000
mean    50.500000   37.910000   73084.673469         9.571429
std     29.011492   12.219454   27434.662636         6.000000
min      1.000000   18.000000   30854.000000         0.000000
25%     25.750000   26.750000   47717.500000         4.000000
50%     50.500000   38.000000   73540.000000        10.000000
75%     75.250000   46.250000   96450.750000        15.000000
max    100.000000   59.000000  119045.000000        19.000000

In [233]:
employee_data["Age"].mean()

np.float64(37.91)

In [234]:
employee_data["Age"].max()

np.int64(59)

In [235]:
employee_data[employee_data["Age"] > 50]

,ID,Name,Age,Country,Salary,ExperienceYears,Remote,Department
0,1,Lucy,56,USA,30854.0,15.0,Yes,IT
5,6,Sebastian,56,Japan,117092.0,5.0,Yes,Design
11,12,Riley,53,USA,82662.0,14.0,Yes,Marketing
12,13,Elijah,57,France,42688.0,NaN,No,IT
19,20,Evelyn,55,Brazil,64698.0,16.0,No,Marketing
27,28,Thomas,59,USA,NaN,13.0,No,NaN
32,33,Eleanor,54,Japan,41411.0,2.0,Yes,IT
36,37,Leah,56,Azerbaijan,38680.0,7.0,Yes,IT
48,49,Noah,52,Brazil,51918.0,15.0,No,Marketing
51,52,Ezra,53,Azerbaijan,60306.0,2.0,No,IT
52,53,Dylan,57,Azerbaijan,46646.0,17.0,Yes,Finance
56,57,Lillian,59,France,32049.0,12.0,Yes,Marketing
61,62,Isabella,51,USA,102694.0,15.0,No,IT
63,64,James,53,USA,37400.0,11.0,No,Finance
70,71,Lily,57,France,89040.0,19.0,Yes,Design
77,78,Ryan,58,France,91267.0,7.0,No,Finance
91,92,John,52,Germany,53328.0,12.0,Yes,Finance
92,93,Samuel,52,France,116831.0,17.0,Yes,IT
95,96,Abigail,59,USA,52399.0,16.0,Yes,Finance
96,97,Harper,56,USA,76214.0,18.0,Yes,IT
97,98,Owen,58,France,116416.0,4.0,No,Design

In [236]:
employee_data["Age"].value_counts()

Age
41    6
25    5
56    4
32    4
38    4
19    4
42    4
24    4
31    4
46    3
28    3
53    3
57    3
59    3
45    3
26    3
35    3
21    3
43    3
52    3
40    2
20    2
39    2
50    2
33    2
34    2
58    2
18    2
36    1
47    1
55    1
29    1
44    1
54    1
37    1
23    1
51    1
27    1
48    1
22    1
Name: count, dtype: int64

In [237]:
employee_data["Country"].value_counts()

Country
USA           22
Azerbaijan    18
Brazil        17
France        17
Japan         14
Germany       11
Name: count, dtype: int64

In [238]:
employee_data.groupby("Country")["Salary"].mean()

Country
Azerbaijan    72012.555556
Brazil        76001.882353
France        84260.411765
Germany       62115.000000
Japan         72384.214286
USA           67355.300000
Name: Salary, dtype: float64

SELECT Country, AVG(Salary)

FROM Employees

GROUP BY Country

In [239]:
employee_data.index

RangeIndex(start=0, stop=100, step=1)

In [240]:
employee_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,100.0,50.500000,29.011492,1.0,25.75,50.5,75.25,100.0
Age,100.0,37.910000,12.219454,18.0,26.75,38.0,46.25,59.0
Salary,98.0,73084.673469,27434.662636,30854.0,47717.50,73540.0,96450.75,119045.0
ExperienceYears,98.0,9.571429,6.000000,0.0,4.00,10.0,15.00,19.0

In [241]:
employee_data["Country"]

0            USA
1     Azerbaijan
2        Germany
3            USA
4         Brazil
         ...
95           USA
96           USA
97        France
98           USA
99       Germany
Name: Country, Length: 100, dtype: str

In [242]:
employee_data[["Country", "Name"]]

       Country      Name
0          USA      Lucy
1   Azerbaijan  Victoria
2      Germany  Benjamin
3          USA      Luna
4       Brazil       Zoe
..         ...       ...
95         USA   Abigail
96         USA    Harper
97      France      Owen
98         USA     Ethan
99     Germany   Grayson

[100 rows x 2 columns]

In [243]:
employee_data.drop("Country", axis=1, inplace=True)

In [244]:
employee_data

     ID      Name  Age    Salary  ExperienceYears Remote Department
0     1      Lucy   56   30854.0             15.0    Yes         IT
1     2  Victoria   46   68623.0             11.0    Yes         HR
2     3  Benjamin   32   37392.0              NaN     No  Marketing
3     4      Luna   25   85680.0             13.0     No    Finance
4     5       Zoe   38   76717.0              5.0    Yes     Design
..  ...       ...  ...       ...              ...    ...        ...
95   96   Abigail   59   52399.0             16.0    Yes    Finance
96   97    Harper   56   76214.0             18.0    Yes         IT
97   98      Owen   58  116416.0              4.0     No     Design
98   99     Ethan   45  100271.0              8.0    Yes     Design
99  100   Grayson   24   74064.0             11.0    Yes         HR

[100 rows x 7 columns]

In [245]:
employee_data.drop(0, axis=0, inplace=True)
employee_data

     ID       Name  Age    Salary  ExperienceYears Remote Department
1     2   Victoria   46   68623.0             11.0    Yes         HR
2     3   Benjamin   32   37392.0              NaN     No  Marketing
3     4       Luna   25   85680.0             13.0     No    Finance
4     5        Zoe   38   76717.0              5.0    Yes     Design
5     6  Sebastian   56  117092.0              5.0    Yes     Design
..  ...        ...  ...       ...              ...    ...        ...
95   96    Abigail   59   52399.0             16.0    Yes    Finance
96   97     Harper   56   76214.0             18.0    Yes         IT
97   98       Owen   58  116416.0              4.0     No     Design
98   99      Ethan   45  100271.0              8.0    Yes     Design
99  100    Grayson   24   74064.0             11.0    Yes         HR

[99 rows x 7 columns]

In [246]:
employee_data.shape

(99, 7)

In [247]:
employee_data.set_index("Name", inplace=True)

In [248]:
employee_data

            ID  Age    Salary  ExperienceYears Remote Department
Name
Victoria     2   46   68623.0             11.0    Yes         HR
Benjamin     3   32   37392.0              NaN     No  Marketing
Luna         4   25   85680.0             13.0     No    Finance
Zoe          5   38   76717.0              5.0    Yes     Design
Sebastian    6   56  117092.0              5.0    Yes     Design
...        ...  ...       ...              ...    ...        ...
Abigail     96   59   52399.0             16.0    Yes    Finance
Harper      97   56   76214.0             18.0    Yes         IT
Owen        98   58  116416.0              4.0     No     Design
Ethan       99   45  100271.0              8.0    Yes     Design
Grayson    100   24   74064.0             11.0    Yes         HR

[99 rows x 6 columns]

In [249]:
employee_data.loc['Zoe']

ID                       5
Age                     38
Salary             76717.0
ExperienceYears        5.0
Remote                 Yes
Department          Design
Name: Zoe, dtype: object

In [250]:
employee_data.iloc[4]

ID                        6
Age                      56
Salary             117092.0
ExperienceYears         5.0
Remote                  Yes
Department           Design
Name: Sebastian, dtype: object

In [251]:
employee_data.dtypes

ID                   int64
Age                  int64
Salary             float64
ExperienceYears    float64
Remote                 str
Department             str
dtype: object

In [252]:
employee_data["Department"].str.lower()

Name
Victoria            hr
Benjamin     marketing
Luna           finance
Zoe             design
Sebastian       design
               ...
Abigail        finance
Harper              it
Owen            design
Ethan           design
Grayson             hr
Name: Department, Length: 99, dtype: str

In [253]:
employee_data["Department"].str.contains("Design")

Name
Victoria     False
Benjamin     False
Luna         False
Zoe           True
Sebastian     True
             ...
Abigail      False
Harper       False
Owen          True
Ethan         True
Grayson      False
Name: Department, Length: 99, dtype: bool

In [254]:
employee_data["Age"] += 1
employee_data["Age"]

Name
Victoria     47
Benjamin     33
Luna         26
Zoe          39
Sebastian    57
             ..
Abigail      60
Harper       57
Owen         59
Ethan        46
Grayson      25
Name: Age, Length: 99, dtype: int64

In [255]:
employee_data.rename(columns={"Salary":"Maaş"},inplace=True)
employee_data

            ID  Age      Maaş  ExperienceYears Remote Department
Name
Victoria     2   47   68623.0             11.0    Yes         HR
Benjamin     3   33   37392.0              NaN     No  Marketing
Luna         4   26   85680.0             13.0     No    Finance
Zoe          5   39   76717.0              5.0    Yes     Design
Sebastian    6   57  117092.0              5.0    Yes     Design
...        ...  ...       ...              ...    ...        ...
Abigail     96   60   52399.0             16.0    Yes    Finance
Harper      97   57   76214.0             18.0    Yes         IT
Owen        98   59  116416.0              4.0     No     Design
Ethan       99   46  100271.0              8.0    Yes     Design
Grayson    100   25   74064.0             11.0    Yes         HR

[99 rows x 6 columns]

In [256]:
employee_data.sort_values(by="Age")

          ID  Age      Maaş  ExperienceYears Remote Department
Name
Leo       86   19   51357.0             19.0     No     Design
Ava       81   19   68360.0              4.0    Yes     Design
Scarlett  17   20   82083.0              3.0     No         HR
Olivia    21   20  110623.0             11.0    Yes         IT
Julian    55   20   46371.0              6.0     No     Design
...       ..  ...       ...              ...    ...        ...
Owen      98   59  116416.0              4.0     No     Design
Ryan      78   59   91267.0              7.0     No    Finance
Lillian   57   60   32049.0             12.0    Yes  Marketing
Thomas    28   60       NaN             13.0     No        NaN
Abigail   96   60   52399.0             16.0    Yes    Finance

[99 rows x 6 columns]

In [257]:
employee_data.sort_values(by="Age", ascending=False)

          ID  Age      Maaş  ExperienceYears Remote Department
Name
Thomas    28   60       NaN             13.0     No        NaN
Abigail   96   60   52399.0             16.0    Yes    Finance
Lillian   57   60   32049.0             12.0    Yes  Marketing
Owen      98   59  116416.0              4.0     No     Design
Ryan      78   59   91267.0              7.0     No    Finance
...       ..  ...       ...              ...    ...        ...
Scarlett  17   20   82083.0              3.0     No         HR
Julian    55   20   46371.0              6.0     No     Design
Charles   44   20   31802.0             16.0    Yes     Design
Ava       81   19   68360.0              4.0    Yes     Design
Leo       86   19   51357.0             19.0     No     Design

[99 rows x 6 columns]

In [258]:
employee_data.isna().sum()

ID                 0
Age                0
Maaş               2
ExperienceYears    2
Remote             0
Department         1
dtype: int64

In [260]:
employee_data

            ID  Age      Maaş  ExperienceYears Remote Department
Name
Victoria     2   47   68623.0             11.0    Yes         HR
Benjamin     3   33   37392.0              NaN     No  Marketing
Luna         4   26   85680.0             13.0     No    Finance
Zoe          5   39   76717.0              5.0    Yes     Design
Sebastian    6   57  117092.0              5.0    Yes     Design
...        ...  ...       ...              ...    ...        ...
Abigail     96   60   52399.0             16.0    Yes    Finance
Harper      97   57   76214.0             18.0    Yes         IT
Owen        98   59  116416.0              4.0     No     Design
Ethan       99   46  100271.0              8.0    Yes     Design
Grayson    100   25   74064.0             11.0    Yes         HR

[99 rows x 6 columns]

In [265]:
employee_data["Maaş"].fillna(employee_data["Maaş"].mean(), inplace=True)

C:\Users\mr13\AppData\Local\Temp\ipykernel_11708\3166139500.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  employee_data["Maaş"].fillna(employee_data["Maaş"].mean(), inplace=True)

Name
Victoria      68623.0
Benjamin      37392.0
Luna          85680.0
Zoe           76717.0
Sebastian    117092.0
               ...
Abigail       52399.0
Harper        76214.0
Owen         116416.0
Ethan        100271.0
Grayson       74064.0
Name: Maaş, Length: 99, dtype: float64

In [266]:
employee_data

            ID  Age      Maaş  ExperienceYears Remote Department
Name
Victoria     2   47   68623.0        11.000000    Yes         HR
Benjamin     3   33   37392.0     73520.041237     No  Marketing
Luna         4   26   85680.0        13.000000     No    Finance
Zoe          5   39   76717.0         5.000000    Yes     Design
Sebastian    6   57  117092.0         5.000000    Yes     Design
...        ...  ...       ...              ...    ...        ...
Abigail     96   60   52399.0        16.000000    Yes    Finance
Harper      97   57   76214.0        18.000000    Yes         IT
Owen        98   59  116416.0         4.000000     No     Design
Ethan       99   46  100271.0         8.000000    Yes     Design
Grayson    100   25   74064.0        11.000000    Yes         HR

[99 rows x 6 columns]

In [267]:
employee_data["Department"].unique()

<StringArray>
['HR', 'Marketing', 'Finance', 'Design', 'IT', nan]
Length: 6, dtype: str

In [268]:
employee_data["Department"].nunique()

5

In [269]:
employee_data.set_index("ID", inplace=True)

In [270]:
employee_data

     Age      Maaş  ExperienceYears Remote Department
ID
2     47   68623.0        11.000000    Yes         HR
3     33   37392.0     73520.041237     No  Marketing
4     26   85680.0        13.000000     No    Finance
5     39   76717.0         5.000000    Yes     Design
6     57  117092.0         5.000000    Yes     Design
..   ...       ...              ...    ...        ...
96    60   52399.0        16.000000    Yes    Finance
97    57   76214.0        18.000000    Yes         IT
98    59  116416.0         4.000000     No     Design
99    46  100271.0         8.000000    Yes     Design
100   25   74064.0        11.000000    Yes         HR

[99 rows x 5 columns]

In [271]:
employee_data.reset_index(inplace=True)

In [272]:
employee_data

     ID  Age      Maaş  ExperienceYears Remote Department
0     2   47   68623.0        11.000000    Yes         HR
1     3   33   37392.0     73520.041237     No  Marketing
2     4   26   85680.0        13.000000     No    Finance
3     5   39   76717.0         5.000000    Yes     Design
4     6   57  117092.0         5.000000    Yes     Design
..  ...  ...       ...              ...    ...        ...
94   96   60   52399.0        16.000000    Yes    Finance
95   97   57   76214.0        18.000000    Yes         IT
96   98   59  116416.0         4.000000     No     Design
97   99   46  100271.0         8.000000    Yes     Design
98  100   25   74064.0        11.000000    Yes         HR

[99 rows x 6 columns]